apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./steps/06-extras/gitops/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
